apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-template
  name: web-template
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8068
      protocol: TCP
      targetPort: 8068
  selector:
    app: web-template

